name: mcp_dart_sdk
description: A Dart implementation of the Model Context Protocol (MCP) for seamless integration between LLM applications and external data sources/tools.
version: 0.1.0
repository: https://github.com/Ayobami-00/mcp_dart_sdk

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  http: ^1.1.0
  logging: ^1.2.0
  meta: ^1.9.1
  uuid: ^4.0.0
  async: ^2.11.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  mockito: ^5.4.2

topics:
  - ai
  - llm
  - protocol
  - tooling 